apiVersion: v1
kind: Service
metadata:
  labels:
    service: memcached
  name: memcached-svr
spec:
  # clusterIP: None  # Headless service
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    pod: memcached
