apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached-srv
  name: memcached-srv
spec:
  # clusterIP: None  # Headless service
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: memcached-pod
