apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovh-api-deployment
  labels:
    deployment: ovh-api
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: ovh-api
  template:
    metadata:
      labels:
        pod: ovh-api
    spec:
      containers:
      - name: ovh-api-cnt
        image: ticapix/ovh-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: MEMCACHED_PORT
          value: "11211"
        - name: MEMCACHED_HOST
          value: "memcached-srv"
